# Generated by Django 4.2.1 on 2023-05-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0002_alter_mywork_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='photo',
            field=models.ImageField(default=1, upload_to='mywork/'),
            preserve_default=False,
        ),
    ]
