# Generated by Django 4.2.1 on 2023-05-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0003_mywork_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
