# Generated by Django 4.2.1 on 2023-05-19 06:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0005_theory_delete_mywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mywork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('htmlcontent', tinymce.models.HTMLField()),
                ('photo', models.ImageField(upload_to='mywork/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Theory',
        ),
    ]
