# Generated by Django 4.2.1 on 2023-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='meta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
