# Generated by Django 4.2.1 on 2023-05-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0007_mywork_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywork',
            old_name='meta',
            new_name='metaname',
        ),
    ]
