# Generated by Django 4.2.1 on 2023-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0010_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='meta',
            field=models.CharField(max_length=80),
        ),
    ]
