# Generated by Django 4.2.1 on 2023-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0012_alter_mywork_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='content',
            field=models.CharField(choices=[('현장이야기', '현장이야기'), ('영화연출', '영화연출')], max_length=20),
        ),
    ]
