# Generated by Django 4.2.1 on 2023-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0013_alter_mywork_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='content',
            field=models.CharField(choices=[('현장이야기', '현장이야기'), ('영화연출', '영화연출')]),
        ),
    ]
