# Generated by Django 4.2.1 on 2023-07-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0014_alter_mywork_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '2. 댓글'},
        ),
        migrations.AlterModelOptions(
            name='mywork',
            options={'verbose_name_plural': '1. 영화 이야기 포스팅'},
        ),
    ]
