# Generated by Django 4.2.1 on 2023-07-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0015_alter_comment_options_alter_mywork_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='content',
            field=models.CharField(choices=[('영화추천', '영화추천'), ('영화연출', '영화연출'), ('현장이야기', '현장이야기')]),
        ),
    ]
