# Generated by Django 4.2.1 on 2023-07-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0016_alter_mywork_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='content',
            field=models.CharField(choices=[('영화연출', '영화연출'), ('영화추천', '영화추천'), ('현장이야기', '현장이야기')]),
        ),
    ]
