# Generated by Django 4.2.1 on 2023-05-18 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mywork', '0004_mywork_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mywork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.mywork')),
            ],
        ),
    ]
