# Generated by Django 4.2.1 on 2023-05-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_alter_genre_moviesubject'),
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='mywork',
        ),
        migrations.AddField(
            model_name='list',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
