# Generated by Django 4.2.1 on 2024-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_meetingdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingdate',
            options={'verbose_name_plural': '우리의 디데이'},
        ),
        migrations.AddField(
            model_name='meetingdate',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingdate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='secret/'),
        ),
    ]
