# Generated by Django 4.2.1 on 2023-05-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0004_mywork_content'),
        ('myprofile', '0003_rename_list_list_movie_list_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_mywork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mywork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywork.mywork')),
            ],
        ),
    ]
