# Generated by Django 4.2.1 on 2024-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_meetingdate_options_meetingdate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
