# Generated by Django 4.2.1 on 2023-05-21 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0021_django_content_network_content_physics_content'),
        ('myprofile', '0004_list_mywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.physics')),
            ],
        ),
        migrations.CreateModel(
            name='List_network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.network')),
            ],
        ),
    ]
