# Generated by Django 4.2.1 on 2023-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_list_physics_list_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
