# Generated by Django 4.2.1 on 2023-05-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='views',
            old_name='views',
            new_name='count',
        ),
    ]
