# Generated by Django 4.2.1 on 2023-05-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_rename_views_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_movie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='list_mywork',
            name='mywork',
        ),
        migrations.RemoveField(
            model_name='list_network',
            name='network',
        ),
        migrations.RemoveField(
            model_name='list_physics',
            name='physics',
        ),
        migrations.DeleteModel(
            name='List_django',
        ),
        migrations.DeleteModel(
            name='List_movie',
        ),
        migrations.DeleteModel(
            name='List_mywork',
        ),
        migrations.DeleteModel(
            name='List_network',
        ),
        migrations.DeleteModel(
            name='List_physics',
        ),
    ]
