# Generated by Django 4.2.1 on 2023-05-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_alter_engineer_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='django',
            old_name='moviestudy',
            new_name='engineerkey',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='moviestudy',
            new_name='engineerkey',
        ),
        migrations.RenameField(
            model_name='physics',
            old_name='moviestudy',
            new_name='engineerkey',
        ),
    ]
