# Generated by Django 4.2.1 on 2023-05-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_rename_moviestudy_django_engineerkey_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='django',
            unique_together={('engineerkey', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('engineerkey', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='physics',
            unique_together={('engineerkey', 'subject')},
        ),
    ]
