# Generated by Django 4.2.1 on 2023-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0004_network_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='code',
            field=models.CharField(choices=[('ROS', 'ROS'), ('이론', '이론'), ('대학교', '대학교')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
