# Generated by Django 4.2.1 on 2023-05-13 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0004_alter_django_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='django',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='physics',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='django',
            name='engineerkey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engineer.engineer'),
        ),
        migrations.AlterField(
            model_name='network',
            name='engineerkey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engineer.engineer'),
        ),
        migrations.AlterField(
            model_name='physics',
            name='engineerkey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engineer.engineer'),
        ),
    ]
