# Generated by Django 4.2.1 on 2023-05-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0005_alter_django_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='engineer/')),
                ('create_date', models.DateTimeField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.engineer')),
            ],
        ),
    ]
