# Generated by Django 4.2.1 on 2023-05-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0006_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Django_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='django/')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.django')),
            ],
        ),
        migrations.CreateModel(
            name='Network_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='network/')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.network')),
            ],
        ),
        migrations.CreateModel(
            name='Physics_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='physics/')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.physics')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
