# Generated by Django 4.2.1 on 2023-05-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0007_django_image_network_image_physics_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='create_date',
        ),
    ]
