# Generated by Django 4.2.1 on 2023-05-13 22:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0008_remove_engineer_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='htmlcontent',
            field=tinymce.models.HTMLField(blank=True, verbose_name='tinymce'),
        ),
    ]
