# Generated by Django 4.2.1 on 2023-05-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0009_physics_htmlcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='htmlcontent',
        ),
    ]
