# Generated by Django 4.2.1 on 2023-05-13 23:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0011_physics_htmlcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physics',
            name='htmlcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
