# Generated by Django 4.2.1 on 2023-05-14 00:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0012_alter_physics_htmlcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='django',
            name='htmlcontent',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='htmlcontent',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='django',
            name='create_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='create_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
