# Generated by Django 4.2.1 on 2023-05-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0013_django_htmlcontent_network_htmlcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='network',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='subject',
        ),
    ]
