# Generated by Django 4.2.1 on 2023-05-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0014_remove_django_subject_remove_network_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='content',
        ),
        migrations.RemoveField(
            model_name='network',
            name='content',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='content',
        ),
        migrations.AddField(
            model_name='django',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physics',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
