# Generated by Django 4.2.1 on 2023-05-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0015_remove_django_content_remove_network_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='physics',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
