# Generated by Django 4.2.1 on 2023-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0016_alter_django_create_date_alter_network_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
