# Generated by Django 4.2.1 on 2023-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0018_alter_network_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='django',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='physics',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
