# Generated by Django 4.2.1 on 2023-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0023_django_meta_network_meta_physics_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django',
            name='meta',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='network',
            name='meta',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='physics',
            name='meta',
            field=models.CharField(max_length=80),
        ),
    ]
