# Generated by Django 4.2.1 on 2023-05-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0024_alter_django_meta_alter_network_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django',
            name='meta',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='network',
            name='meta',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='physics',
            name='meta',
            field=models.CharField(max_length=130),
        ),
    ]
