# Generated by Django 4.2.1 on 2023-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0024_alter_django_meta_alter_network_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='django',
            name='code',
            field=models.CharField(choices=[('튜토리얼', '튜토리얼'), ('문법', '문법'), ('템플릿', '템플릿')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
