# Generated by Django 4.2.1 on 2023-06-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0026_django_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='engineerkey',
        ),
        migrations.RemoveField(
            model_name='network',
            name='engineerkey',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='engineerkey',
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
