# Generated by Django 4.2.1 on 2023-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0027_remove_django_engineerkey_remove_network_engineerkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django',
            name='meta',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='network',
            name='meta',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='physics',
            name='meta',
            field=models.CharField(max_length=130),
        ),
    ]
