# Generated by Django 4.2.1 on 2023-07-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0029_alter_django_content_alter_network_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='content',
        ),
        migrations.RemoveField(
            model_name='network',
            name='content',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='content',
        ),
    ]
