# Generated by Django 4.2.1 on 2023-07-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0030_remove_django_content_remove_network_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_django',
            options={'verbose_name_plural': '4. 디장고 댓글'},
        ),
        migrations.AlterModelOptions(
            name='comment_network',
            options={'verbose_name_plural': '6. 네트워크 댓글'},
        ),
        migrations.AlterModelOptions(
            name='comment_physics',
            options={'verbose_name_plural': '2. 물리학 댓글'},
        ),
        migrations.AlterModelOptions(
            name='django',
            options={'verbose_name_plural': '3. 디장고 포스팅'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name_plural': '5. 네트워크 포스팅'},
        ),
        migrations.AlterModelOptions(
            name='physics',
            options={'verbose_name_plural': '1. 물리학 포스팅'},
        ),
        migrations.RemoveField(
            model_name='django',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='network',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='hits',
        ),
    ]
