# Generated by Django 4.2.1 on 2023-08-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0032_network_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='code',
        ),
    ]
