# Generated by Django 4.2.1 on 2023-05-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='content',
            new_name='ott',
        ),
    ]
