# Generated by Django 4.2.1 on 2023-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_content_genre_ott'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='question',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.BooleanField(default=False),
        ),
    ]
