# Generated by Django 4.2.1 on 2023-05-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_question_genre_subject_genre_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='subject',
            new_name='moviesubject',
        ),
    ]
