# Generated by Django 4.2.1 on 2023-05-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_subject_genre_moviesubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
    ]
