# Generated by Django 4.2.1 on 2023-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.ImageField(default=1, upload_to='movie/'),
            preserve_default=False,
        ),
    ]
