# Generated by Django 4.2.1 on 2023-05-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='ott',
        ),
    ]
