# Generated by Django 4.2.1 on 2023-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_genre_ott'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.CharField(choices=[('commercial', '상업영화'), ('ott', 'OTT 스트리밍')], max_length=20),
        ),
    ]
