# Generated by Django 4.2.1 on 2023-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_genre_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.CharField(choices=[('commercial', '상업영화'), ('ott', 'OTT 오리지널'), ('drama', '드라마')], max_length=20),
        ),
    ]
