# Generated by Django 4.2.1 on 2023-05-14 01:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_genre_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='content',
        ),
        migrations.AddField(
            model_name='movie',
            name='htmlcontent',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
