# Generated by Django 4.2.1 on 2023-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_movie_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.CharField(choices=[('상업영화', '상업영화'), ('OTT 오리지널', 'OTT 오리지널'), ('드라마', '드라마')], max_length=20),
        ),
    ]
