# Generated by Django 4.2.1 on 2023-05-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_genre_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='moviesubject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
