# Generated by Django 4.2.1 on 2023-05-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_movie_genre_delete_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Screening',
            new_name='screening',
        ),
    ]
