# Generated by Django 4.2.1 on 2023-05-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='meta',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
